run:
  timeout: 5m

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
    enable-all: true

linters:
  disable-all: true
  enable:
    - deadcode
#    - errcheck
#    - gosimple
#    - govet
#    - ineffassign
#    - staticcheck
#    - structcheck
#    - typecheck
#    - unused
#    - varcheck
#    - bodyclose
#    - depguard
#    - dogsled
#    - dupl
#    - goconst
#    - gofmt
#    - goimports
#    - golint
#    - goprintffuncname
#    - misspell
#    - nakedret
#    - scopelint
#    - unconvert
#    - whitespace
#    - gocritic

issues:
  exclude-rules:
    - linters:
        - golint
      text: "should have|should be|should replace|stutters|underscore|annoying|error strings should not be capitalized"
    - linters:
        - staticcheck
      text: "SA5008: unknown JSON"
