run:
  timeout: 5m
  modules-download-mode: vendor

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
    enable-all: true

linters:
  disable-all: true
  enable:
    - deadcode
    - gofmt
    - golint
    - gosimple
    - govet
    - ineffassign
    - scopelint
    - structcheck
    - staticcheck
    - unconvert
    - unused
    - varcheck
    - misspell
    - goimports
    # TODO: enable this later
    # - errcheck

